// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfwbsjokktasumghrznk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlmd2Jzam9ra3Rhc3VtZ2hyem5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNTMxNjYsImV4cCI6MjA3MjcyOTE2Nn0.3fWqquCGKV-_9Hv-PAbQNFQ0MFHg6JckI6DPUSsoQGo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});